### PR TITLE
Paginate trades by last execution

### PR DESCRIPTION
**Pull request by vumanhcuongit**
### Change

Add `lastExecutionId` as a parameter to paginate trades.

### CODE REVIEW

**Comment by nubis** [comment]
Hi, this looks great. I'm not familiar with the executionId concept though. Are those sequential? Are they global or a new sequence for every specific wallet? Why is 300 a sensible default?

Thanks !

**Comment by nubis** [comment]
Sorry, I was reading this pull request on my phone while commuting  hence the dumb questions :)

**Comment by nubis** [comment]
Just released a new gem version 0.0.7 including this change.

**Comment by vumanhcuongit** [comment]
💯

**Pull request merged**
